monitor:
  host: 10.224.57.244
  port: 7199
  username: cassandra
  password: cassandra

logging:
  level:
    org:
      springframework:
        security: info

  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  file:
    name: C:/MyProject/cassandra-monitor.log

